name: tic_tac_toe_with_supabase
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  go_router: ^14.2.1
  hive_flutter: ^1.1.0
  supabase_flutter: ^2.5.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
